project_id = "iwcyduqweqmdpehzdnax"

[functions.generate-insights]
verify_jwt = false

[functions.fetch-openaq-data]
verify_jwt = false

[functions.update-real-boundaries]
verify_jwt = false

[functions.initialize-data]
verify_jwt = false
